services:
  - type: web
    name: skillsync-pro-api
    runtime: python
    plan: free
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python -m spacy download en_core_web_sm
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./skillsync.db
      - key: ENV
        value: production