name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Deployment Started
      run: |
        echo "🚀 Deployment to production started"
        echo "Commit: ${{ github.sha }}"
        echo "Triggered by: ${{ github.actor }}"
        
  backend-deploy:
    needs: deploy-notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Trigger Render Deploy
      run: |
        echo "Render will automatically deploy from the main branch"
        # Render auto-deploys on push to main, so no action needed
    
  frontend-deploy:
    needs: deploy-notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Trigger Vercel Deploy
      run: |
        echo "Vercel will automatically deploy from the main branch"
        # Vercel auto-deploys on push to main, so no action needed
  
  verify-deployment:
    needs: [backend-deploy, frontend-deploy]
    runs-on: ubuntu-latest
    steps:
    - name: Wait for deployments
      run: sleep 120
    
    - name: Verify Backend Health
      run: |
        # Try 5 times with 30-second intervals
        for i in {1..5}; do
          response=$(curl -s -o /dev/null -w "%{http_code}" https://skill-sync-pro.onrender.com/health)
          if [ $response -eq 200 ]; then
            echo "✅ Backend is healthy (attempt $i)"
            exit 0
          else
            echo "Attempt $i: Backend returned status $response"
            if [ $i -lt 5 ]; then
              echo "Waiting 30 seconds before retry..."
              sleep 30
            fi
          fi
        done
        echo "❌ Backend health check failed after 5 attempts"
        exit 1
    
    - name: Verify Frontend
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" https://skill-sync-pro-frontend.vercel.app)
        if [ $response -eq 200 ]; then
          echo "✅ Frontend is accessible"
        else
          echo "❌ Frontend check failed with status $response"
          exit 1
        fi
    
    - name: Deployment Complete
      run: |
        echo "✅ Deployment completed successfully!"
        echo "Backend: https://skill-sync-pro.onrender.com"
        echo "Frontend: https://skill-sync-pro-frontend.vercel.app/"