name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Deployment Started
      run: |
        echo "🚀 Deployment to production started"
        echo "Commit: ${{ github.sha }}"
        echo "Triggered by: ${{ github.actor }}"
        
  backend-deploy:
    needs: deploy-notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Trigger Render Deploy
      run: |
        echo "Render will automatically deploy from the main branch"
        echo "Note: Render free tier may take 5-10 minutes to deploy"
    
  frontend-deploy:
    needs: deploy-notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Trigger Vercel Deploy
      run: |
        echo "Vercel will automatically deploy from the main branch"
  
  verify-deployment:
    needs: [backend-deploy, frontend-deploy]
    runs-on: ubuntu-latest
    # Make this job optional - don't fail the pipeline
    continue-on-error: true
    steps:
    - name: Wait for deployments to start
      run: |
        echo "Waiting 2 minutes for deployments to start..."
        sleep 120
    
    - name: Check Backend Health (Optional)
      run: |
        echo "Checking backend health (this may fail on Render free tier)..."
        response=$(curl -s -o /dev/null -w "%{http_code}" https://skillsync-pro-api.onrender.com/health || echo "000")
        
        if [ "$response" = "200" ]; then
          echo "✅ Backend is healthy!"
        else
          echo "⚠️ Backend returned status $response"
          echo "This is expected on Render free tier - the service may need more time to deploy"
          echo "Check deployment status at: https://dashboard.render.com"
        fi
    
    - name: Verify Frontend
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" https://skill-sync-pro.vercel.app || echo "000")
        if [ "$response" = "200" ]; then
          echo "✅ Frontend is accessible"
        else
          echo "⚠️ Frontend returned status $response"
          echo "Check deployment at: https://vercel.com/dashboard"
        fi
    
    - name: Deployment Status
      run: |
        echo "📝 Deployment Summary:"
        echo "- Frontend: https://skill-sync-pro.vercel.app"
        echo "- Backend: https://skillsync-pro-api.onrender.com"
        echo ""
        echo "Note: Render free tier services sleep after 15 minutes of inactivity"
        echo "First request may take 30-60 seconds to wake up the service"